# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "ML - Photos"
subtitle: ""
author: "Mauricio Laine"
header:
 title: "Photographies"
 subtitle: "by Mauricio Laine"
footer:
 name: "Hi!, my name is Mauricio Laine"
 bio: "I am a software developer who likes taking photos, hiking and traveling when not coding."
 github: ""
web_design: "Ram Patra & AJ"
social_urls:
  # facebook: ""
  # twitter: ""
  # instagram: ""
  # dribbble: ""
  linkedin: "https://www.linkedin.com/in/mauriciolaine/"
  github: "https://github.com/mauroLaine"
